# Generated by Django 5.0 on 2024-01-09 09:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('matricule', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nom', models.TextField(blank=True, null=True)),
                ('prenom', models.TextField(blank=True, null=True)),
                ('fonction', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('password', models.TextField()),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('matricule', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nom', models.TextField(blank=True, null=True)),
                ('prenom', models.TextField(blank=True, null=True)),
                ('département_svc', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ArriveeRetourEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrive', models.TimeField(blank=True, null=True)),
                ('heure_retour', models.TimeField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivee_retour_employe', to='webserver.employe')),
            ],
            options={
                'unique_together': {('date', 'employe')},
            },
        ),
        migrations.CreateModel(
            name='ArriveeRetourStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrive', models.TimeField(blank=True, null=True)),
                ('heure_retour', models.TimeField(blank=True, null=True)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivee_retour_stagiaire', to='webserver.stagiaire')),
            ],
            options={
                'unique_together': {('date', 'stagiaire')},
            },
        ),
    ]
